21880159/QLBH/Pages/MH_NhapHang/MH_SuaHoaDon.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using QuanLyCuaHang_21880159.DAL;
using QuanLyCuaHang_21880159.Entities;
using QuanLyCuaHang_21880159.Service;

namespace QuanLyCuaHang_21880159.Pages.MH_NhapHang
{
    public class MH_SuaHoaDonModel : PageModel
    {
        public bool CoHoaDon;
        [BindProperty]
        public string MaHoaDon { get; set; }
        [BindProperty]
        public int STT { get; set; }
        [BindProperty]
        public int SoLuong { get; set; }
        public string Chuoi;
        public string Chuoi2;
        public string Chuoi3;
        public string Chuoi4;
        [BindProperty(SupportsGet = true)]
        public string id { get; set; }
        public HoaDonNhapHang hd;
        [BindProperty]
        public string NewDate { get; set; }
        public void OnGet()
        {
            Chuoi = string.Empty;
            HoaDonNhapHang? hd2 = LuuTruHoaDonNhapHang.DocHoaDon(id);
            if (hd2 != null)
            {
                hd = hd2.Value;
            }
            CoHoaDon = hd2 != null;
            if (!CoHoaDon)
            {
                Chuoi = "Không tìm thấy hóa đơn!";
            }
        }

        public void OnPostRemove()
        {
            //bool kq = XuLyHoaDonNhapHang.XoaSanPham(MaHoaDon, STT);
            //if (kq)
            //{
            //    Chuoi2 = "Xóa sản phẩm thành công!";
            //}
            //else
            //{
            //    Chuoi2 = "Xóa sản phẩm không thành công!";
            //}
            //HoaDonNhapHang? hd2 = LuuTruHoaDonNhapHang.DocHoaDon(MaHoaDon);
            //if (hd2 != null)
            //{
            //    hd = hd2.Value;
            //}
            //CoHoaDon = hd2 != null;
            //if (!CoHoaDon)
            //{
            //    Chuoi2 = "Không tìm thấy hóa đơn!";
            //}
        }
        public void OnPostDateEdit()
        {
            bool kq = XuLyHoaDonNhapHang.SuaNgayHoaDon(NewDate, MaHoaDon);
            if (kq)
            {
                Chuoi3 = "Sửa ngày thành công!";
            }
            else
            {
                Chuoi3 = "Sửa ngày không thành công!";
            }
            HoaDonNhapHang? hd2 = LuuTruHoaDonNhapHang.DocHoaDon(MaHoaDon);
            if (hd2 != null)
            {
                hd = hd2.Value;
            }
            CoHoaDon = hd2 != null;
            if (!CoHoaDon)
            {
                Chuoi3 = "Không tìm thấy hóa đơn!";
            }
        }
    }
}

21880159/QLBH/Pages/MH_NhapHang/MH_TimKiem.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using QuanLyCuaHang_21880159.DAL;
using QuanLyCuaHang_21880159.Entities;
using QuanLyCuaHang_21880159.Service;

namespace QuanLyCuaHang_21880159.Pages.MH_NhapHang
{
    public class MH_TimKiemModel : PageModel
    {
        public HoaDonNhapHang hd2;
        public List<HoaDonNhapHang> dshd;
        [BindProperty]
        public string Keyword { get; set; }
        [BindProperty]
        public int GiaTienNhap { get; set; }
        [BindProperty]
        public int SoLuong { get; set; }
        public void OnGet()
        {
            dshd = LuuTruHoaDonNhapHang.DocDSHoaDon();
        }
        public void OnPost()
        {
            dshd = XuLyHoaDonNhapHang.TimKiem(Keyword);
        }
    }
}

21880159/QLBH/Pages/MH_NhapHang/MH_XoaHoaDon.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using QuanLyCuaHang_21880159.DAL;
using QuanLyCuaHang_21880159.Entities;
using QuanLyCuaHang_21880159.Service;

namespace QuanLyCuaHang_21880159.Pages.MH_NhapHang
{
    public class MH_XoaHoaDonModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string id { get; set; }
        public string MaHoaDon;
        public bool CoHoaDon;
        public string Chuoi;
        public void OnGet()
        {
            Chuoi = string.Empty;
            HoaDonNhapHang? hd = LuuTruHoaDonNhapHang.DocHoaDon(id);
            CoHoaDon = hd != null;
            if (!CoHoaDon)
            {
                Chuoi = "Không tồn tại mã hóa đơn!";
            }
        }
        public void OnPost()
        {
            //bool kq = XuLyHoaDonNhapHang.XoaHD(id);
            //if (kq)
            //{
            //    Chuoi = "Xóa thành công!";
            //}
            //else
            //{
            //    Chuoi = "Xóa không thành công!";
            //}
        }
    }
}

21880159/QLBH/Pages/MH_XuatHang/MH_CTHDXuatHang.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using QuanLyCuaHang_21880159.DAL;
using QuanLyCuaHang_21880159.Entities;
using QuanLyCuaHang_21880159.Service;

namespace QuanLyCuaHang_21880159.Pages.MH_XuatHang
{
    public class MH_CTHDXuatHangModel : PageModel
    {
        public HoaDonXuatHang hd;
        public bool CoHD;
        public string Chuoi;
        [BindProperty(SupportsGet = true)]
        public string id { get; set; }
        public void OnGet()
        {
            Chuoi = string.Empty;
            List<HoaDonXuatHang> dshd = LuuTruHoaDonXuatHang.DocDSHoaDon();
            hd = dshd[dshd.Count - 1];
            CoHD = true;
            if (!string.IsNullOrEmpty(id))
            {
                HoaDonXuatHang? hd2 = LuuTruHoaDonXuatHang.DocHoaDon(id);
                if (hd2 != null)
                {
                    hd = hd2.Value;
                }
                CoHD = hd2 != null;
                if (!CoHD)
                {
                    Chuoi = "Không tồn tại hóa đơn!";
                }
            }
        }
        public void OnPost()
        {
        }
    }
}

21880159/QLBH/Pages/MH_XuatHang/MH_SuaHoaDon.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using QuanLyCuaHang_21880159.DAL;
using QuanLyCuaHang_21880159.Entities;
using QuanLyCuaHang_21880159.Service;

namespace QuanLyCuaHang_21880159.Pages.MH_XuatHang
{
    public class MH_SuaHoaDonModel : PageModel
    {
        public bool CoHoaDon;
        [BindProperty]
        public string MaHoaDon { get; set; }
        [BindProperty]
        public int STT { get; set; }
        [BindProperty]
        public int SoLuong { get; set; }
        public string Chuoi;
        public string Chuoi2;
        public string Chuoi3;
        public string Chuoi4;
        [BindProperty(SupportsGet = true)]
        public string id { get; set; }
        public HoaDonXuatHang hd;
        [BindProperty]
        public string NewDate { get; set; }
        public void OnGet()
        {
            Chuoi = string.Empty;
            HoaDonXuatHang? hd2 = LuuTruHoaDonXuatHang.DocHoaDon(id);
            if (hd2 != null)
            {
                hd = hd2.Value;
            }
            CoHoaDon = hd2 != null;
            if (!CoHoaDon)
            {
                Chuoi = "Không tìm thấy hóa đơn!";
            }
        }

        public void OnPostRemove()
        {
            bool kq = XuLyHoaDonXuatHang.XoaSanPham(MaHoaDon, STT);
            if (kq)
            {
                Chuoi2 = "Xóa sản phẩm thành công!";
            }
            else
            {
                Chuoi2 = "Xóa sản phẩm không thành công!";
            }
            HoaDonXuatHang? hd2 = LuuTruHoaDonXuatHang.DocHoaDon(MaHoaDon);
            if (hd2 != null)
            {
                hd = hd2.Value;
            }
            CoHoaDon = hd2 != null;
            if (!CoHoaDon)
            {
                Chuoi2 = "Không tìm thấy hóa đơn!";
            }
        }
        public void OnPostDateEdit()
        {
            bool kq = XuLyHoaDonXuatHang.SuaNgayHoaDon(NewDate, MaHoaDon);
            if (kq)
            {
                Chuoi3 = "Sửa ngày thành công!";
            }
            else
            {
                Chuoi3 = "Sửa ngày không thành công!";
            }
            HoaDonXuatHang? hd2 = LuuTruHoaDonXuatHang.DocHoaDon(MaHoaDon);
            if (hd2 != null)
            {
                hd = hd2.Value;
            }
            CoHoaDon = hd2 != null;
            if (!CoHoaDon)
            {
                Chuoi3 = "Không tìm thấy hóa đơn!";
            }
        }
    }
}

21880159/QLBH/Pages/MH_XuatHang/MH_TaoHoaDonXuatHang.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using QuanLyCuaHang_21880159.DAL;
using QuanLyCuaHang_21880159.Entities;
using QuanLyCuaHang_21880159.Service;

namespace QuanLyCuaHang_21880159.Pages.MH_XuatHang
{
    public class MH_TaoHoaDonXuatHangModel : PageModel
    {
        public string Chuoi;
        public string Chuoi2;
        public string Chuoi3;
        public bool CoSanPham;
        public bool CheckSoLuong;
        public SanPham? sp;
        public SanPham sp2;

        public List<SanPham> dssp;
        [BindProperty]
        public int SearchOptions { get; set; }
        [BindProperty]
        public string Keyword { get; set; }
        [BindProperty(SupportsGet = true)]
        public string id { get; set; }
        [BindProperty]
        public int SoLuong { get; set; }
        [BindProperty]
        public string MaSanPham { get; set; }
        public List<SanPhamHoaDon> dsspThem;
        public SanPhamHoaDon sphd;
        public void OnGet()
        {

            //Chuoi2 = string.Empty;
            //Chuoi = string.Empty;
            //dssp = LuuTruSanPham.DocDSSanPham();
            //sp = XuLySanPham.DocSanPham(id);
            //if (sp != null)
            //{
            //    sp2 = sp.Value;
            //}
            //else
            //{
            //    Chuoi = "Không tìm thấy sản phẩm!";
            //}
            //CoSanPham = sp != null;

        }
        public void OnPostSearch()
        {
            //dssp = XuLySanPham.TimKiem(SearchOptions, Keyword);
        }
        public void OnPostAdd()
        {
            dssp = LuuTruSanPham.DocDSSanPham();
            //dsspThem = LuuTruHoaDonXuatHang.DocDSSPXuatHang();
            //SanPham? sp3 = XuLySanPham.DocSanPham(MaSanPham);
            //if (sp3 != null)
            //{
            //    SanPham sp4 = sp3.Value;
            //    Console.WriteLine(sp4.SoLuong);
            //    if (SoLuong > sp4.SoLuong)
            //    {
            //        Chuoi3 = "Số lượng xuất không thể lớn hiện số lượng hiện có!";
            //        return;
            //    }
            //    sp4.SoLuong = SoLuong;
            //    sphd.MaSanPham = sp4.MaSanPham;
            //    sphd.TenSanPham = sp4.TenSanPham;
            //    sphd.HanSuDung = sp4.HanSuDung;
            //    sphd.CtySanXuat = sp4.CtySanXuat;
            //    sphd.MaLoaiHang = sp4.MaLoaiHang;
            //    sphd.GiaSanPham = sp4.GiaSanPham;
            //    sphd.SoLuong = sp4.SoLuong;
            //    sphd.ThanhTien = SoLuong * sp4.GiaSanPham;
            //    LuuTruHoaDonXuatHang.LuuSPXuatHang(sphd);
            //}
            //List<SanPhamHoaDon> tsdsspHoaDon = LuuTruHoaDonXuatHang.DocDSSPXuatHang();
            //for (int i = 0; i < tsdsspHoaDon.Count; i++)
            //{
            //    SanPhamHoaDon sphd2 = tsdsspHoaDon[i];
            //    sphd2.STT = i + 1;
            //    tsdsspHoaDon[i] = sphd2;
            //}
            //LuuTruHoaDonXuatHang.LuuDSSPXuatHang(tsdsspHoaDon);
            //dsspThem = tsdsspHoaDon;
        }
        public void OnPostCreate()
        {
            Chuoi2 = string.Empty;
            dssp = LuuTruSanPham.DocDSSanPham();
            dsspThem = LuuTruHoaDonXuatHang.DocDSSPXuatHang();
            bool kq = LuuTruHoaDonXuatHang.XoaDanhSachSPXuatHang();
            if (dsspThem.Count == 0)
            {
                Chuoi2 = "Hóa đơn không có sản phẩm!";
            }
            else
            {
                string hd = XuLyHoaDonXuatHang.TaoHoaDon(dsspThem);
                Response.Redirect("/MH_XuatHang/MH_CTHDXuatHang");
            }
        }
    }
}

21880159/QLBH/Pages/MH_XuatHang/MH_TimKiem.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using QuanLyCuaHang_21880159.DAL;
using QuanLyCuaHang_21880159.Entities;
using QuanLyCuaHang_21880159.Service;

namespace QuanLyCuaHang_21880159.Pages.MH_XuatHang
{
    public class MH_TimKiemModel : PageModel
    {
        public HoaDonXuatHang hd2;
        public List<HoaDonXuatHang> dshd;
        [BindProperty]
        public string Keyword { get; set; }
        [BindProperty]
        public int GiaTienNhap { get; set; }
        [BindProperty]
        public int SoLuong { get; set; }
        public void OnGet()
        {
            dshd = LuuTruHoaDonXuatHang.DocDSHoaDon();
        }
        public void OnPost()
        {
            dshd = XuLyHoaDonXuatHang.TimKiem(Keyword);
        }
    }
}

21880159/QLBH/Pages/MH_XuatHang/MH_XoaHoaDon.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using QuanLyCuaHang_21880159.DAL;
using QuanLyCuaHang_21880159.Entities;
using QuanLyCuaHang_21880159.Service;

namespace QuanLyCuaHang_21880159.Pages.MH_XuatHang
{
    public class MH_XoaHoaDonModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string id { get; set; }
        public string MaHoaDon;
        public bool CoHoaDon;
        public string Chuoi;
        public void OnGet()
        {
            Chuoi = string.Empty;
            HoaDonXuatHang? hd = LuuTruHoaDonXuatHang.DocHoaDon(id);
            CoHoaDon = hd != null;
            if (!CoHoaDon)
            {
                Chuoi = "Không tồn tại mã hóa đơn!";
            }
        }
        public void OnPost()
        {
            //bool kq = XuLyHoaDonXuatHang.XoaHD(id);
            //if (kq)
            //{
            //    Chuoi = "Xóa thành công!";
            //}
            //else
            //{
            //    Chuoi = "Xóa không thành công!";
            //}
        }
    }
}

21880159/QLBH/Pages/MH_XuatHang/MH_CTHDXuatHang.cshtml
@page
@model QuanLyCuaHang_21880159.Pages.MH_XuatHang.MH_CTHDXuatHangModel
@using QuanLyCuaHang_21880159.Entities;
@{
}

@if (Model.CoHD)
{
    <h3 style="text-align:center">Chi Tiết Hóa Đơn Xuất Hàng</h3>
    <br />
    <br />

    <p>Mã hóa đơn: @Model.hd.MaHoaDon </p>
    <br />
    <p>Ngày lập hóa đơn: @Model.hd.NgayLap </p>
    <br />
    <table class="table table-bordered table-hover">
        <tr>
            <th>STT</th>
            <th>Tên Sản Phẩm</th>
            <th>Số lượng</th>
            <th>Giá sản phẩm</th>
            <th>Thành tiền</th>
        </tr>
        @foreach (var sp in Model.hd.DSSP)
        {
            <tr>
                <td>@sp.STT</td>
                <td>@sp.TenSanPham</td>
                <td>@sp.SoLuong</td>
                <td>@sp.GiaSanPham</td>
                <td>@sp.ThanhTien</td>
            </tr>
        }

    </table>
    <p><b>Tổng tiền: @Model.hd.TongTien </b></p>
}
@Model.Chuoi
<br />
<a class="btn btn-info" href="/MH_XuatHang/MH_TaoHoaDonXuatHang">Tạo thêm hóa đơn</a>
<a class="btn btn-info" href="/MH_XuatHang/MH_TimKiem">Quay về tìm kiếm</a>

<br />

21880159/QLBH/Pages/MH_XuatHang/MH_SuaHoaDon.cshtml
@page
@model QuanLyCuaHang_21880159.Pages.MH_XuatHang.MH_SuaHoaDonModel
@{
}
@if (Model.CoHoaDon)
{
    <form method="post">
        <h4>Sửa hóa đơn</h4>
        <label>Mã hóa đơn: @Model.hd.MaHoaDon</label>
        <input type="text" name="MaHoaDon" hidden value="@Model.hd.MaHoaDon" class="form-control" />
        <br />
        <label>Ngày tạo hóa đơn</label>
        <input type="text" name="newdate" value="@Model.hd.NgayLap" class="form-control" />
        <input asp-page-handler="dateedit" type="submit" value="Sửa" />
        @Model.Chuoi2
        <h5>Danh sách sản phẩm</h5>
        <br />
        @Model.Chuoi3
        @Model.Chuoi4
        <table class="table table-bordered table-hover">
            <tr>
                <th>STT</th>
                <th>Mã sản phẩm</th>
                <th>Tên sản phẩm</th>
                <th>Số lượng</th>
                <th>Giá tiền</th>
                <th>Thành tiền</th>
                <th>Hành động</th>
            </tr>
            @foreach (var sp in Model.hd.DSSP)
            {
                <tr>
                    <td>@sp.STT</td>
                    <td>@sp.MaLoaiHang</td>
                    <td>@sp.TenSanPham</td>
                    <td>@sp.SoLuong</td>
                    <td>@sp.GiaSanPham</td>
                    <td>@sp.ThanhTien</td>
                    <td>
                        <input asp-page-handler="remove" type="submit" class="btn btn-info" value="Xóa sản phẩm" />
                    </td>
                </tr>
            }
        </table>
        <br />
        <a class="btn btn-info" href="/MH_XuatHang/MH_TimKiem">Quay về tìm kiếm</a>
    </form>
}
@Model.Chuoi

21880159/QLBH/Pages/MH_XuatHang/MH_TaoHoaDonXuatHang.cshtml
@page
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model QuanLyCuaHang_21880159.Pages.MH_XuatHang.MH_TaoHoaDonXuatHangModel
@using QuanLyCuaHang_21880159.Entities
@{
}
<h3 style="text-align:center">Tạo hóa đơn xuất hàng</h3>
<form method="post">
    <label for="searchOptions">Tìm kiếm sản phẩm theo:</label><br />
    <select name="SearchOptions" class="custom-select">
        <option value="1">Mã sản phẩm</option>
        <option value="2">Tên sản phẩm</option>
    </select><br /><br />
    <label>Nhập thông tin tìm kiếm:</label><br>
    <input type="text" name="Keyword" value="" class="form-control" /><br />
    <input asp-page-handler="search" type="submit" value="Tìm kiếm" class="btn btn-info" />
</form>
<br>

<table class="table table-bordered table-hover">
    <tr>
        <th style="text-align : center">Mã sản phẩm</th>
        <th style="text-align : center">Tên sản phẩm</th>
        <th style="text-align : center">Giá nhập</th>
        <th style="text-align : center">Chọn sản phẩm</th>
    </tr>
    @foreach (SanPham s in Model.dssp)
    {
        <tr>
            <td style="text-align : center">@s.MaSanPham</td>
            <td style="text-align : center">@s.TenSanPham</td>
            <td style="text-align : center">@s.GiaSanPham</td>
            <td style="text-align : center">
                <a href="MH_TaoHoaDonXuatHang?id=@s.MaSanPham">Chọn</a>
            </td>
        </tr>
    }
</table>
<br />
<h5>Thêm thông tin sản phẩm</h5>
<h4>@Model.Chuoi3</h4>
<form method="post">
    <table class="table table-bordered table-hover">
        <tr>
            <th style="text-align : center">Mã sản phẩm</th>
            <th style="text-align : center">Tên sản phẩm</th>
            <th style="text-align : center">Số lượng</th>
            <th style="text-align : center">Giá nhập</th>
            <th style="text-align : center">Chọn sản phẩm</th>
        </tr>
        @if (Model.CoSanPham)
        {
            <tr>
                <td style="text-align : center">
                    @Model.sp2.MaSanPham
                    <input type="hidden" name="MaSanPham" value="@Model.sp2.MaSanPham" />
                </td>
                <td style="text-align : center">@Model.sp2.TenSanPham</td>
                <td style="text-align : center">
                    <input type="text" name="SoLuong" value="@Model.sp2.SoLuong" />
                </td>
                <td style="text-align : center">@Model.sp2.GiaSanPham</td>
                <td style="text-align : center">
                    <input type="submit" asp-page-handler="add" value="Lưu" />
                </td>
            </tr>
        }
    </table>
</form>
<br />
<h5>Thêm thông tin hóa đơn</h5>
@Model.Chuoi2
<form method="post">
    <table class="table table-bordered table-hover">
        <tr>
            <th style="text-align : center">STT</th>
            <th style="text-align : center">Mã sản phẩm</th>
            <th style="text-align : center">Tên sản phẩm</th>
            <th style="text-align : center">Số lượng</th>
            <th style="text-align : center">Giá nhập</th>
            <th style="text-align : center">Thành tiền</th>
        </tr>
        @if (Model.dsspThem != null)
        {
            foreach (var s in Model.dsspThem)
            {
                <tr>
                    <td style="text-align : center">@s.STT</td>
                    <td style="text-align : center">@s.MaSanPham</td>
                    <td style="text-align : center">@s.TenSanPham</td>
                    <td style="text-align : center">@s.SoLuong</td>
                    <td style="text-align : center">@s.GiaSanPham</td>
                    <td style="text-align : center">@s.ThanhTien</td>
                </tr>
            }
        }
    </table>
    <input type="submit" asp-page-handler="create" class="btn btn-success" value="Tạo hóa đơn" />
</form>

21880159/QLBH/Pages/MH_XuatHang/MH_TimKiem.cshtml
@page
@model QuanLyCuaHang_21880159.Pages.MH_XuatHang.MH_TimKiemModel
@using QuanLyCuaHang_21880159.Entities;
@{
}

<form method="post">
    <label>Nhập mã hóa đơn:</label><br />
    <input type="text" name="Keyword" value="" class="form-control" class="form-control" /><br>
    <input type="submit" value="Tìm kiếm" class="btn btn-info" />
</form>
<h3 style="text-align:center">Danh sách hóa đơn</h3>
<a href="/MH_XuatHang/MH_TaoHoaDonXuatHang" class="btn btn-outline-info">Tạo hóa đơn</a>
<br />
<br />
<table class="table table-bordered table-hover">
    <tr>
        <th style="text-align:center">Mã hóa đơn</th>
        <th style="text-align:center">Ngày lập</th>
        <th style="text-align:center">Tổng tiền</th>
        <th style="text-align:center">Hành động</th>
    </tr>
    @foreach (var hd in Model.dshd)
    {
        <tr>
            <td>@hd.MaHoaDon</td>
            <td>@hd.NgayLap</td>
            <td>@hd.TongTien</td>
            <td style="text-align:center">
                <a href="/MH_XuatHang/MH_CTHDXuatHang?id=@hd.MaHoaDon">Xem Chi Tiêt</a>
                <a href="/MH_XuatHang/MH_SuaHoaDon?id=@hd.MaHoaDon">Sửa</a>
                <a href="/MH_XuatHang/MH_XoaHoaDon?id=@hd.MaHoaDon">Xóa</a>
            </td>
        </tr>
    }
</table>

21880159/QLBH/Pages/MH_XuatHang/MH_XoaHoaDon.cshtml
@page
@model QuanLyCuaHang_21880159.Pages.MH_XuatHang.MH_XoaHoaDonModel
@{

}
@if (Model.CoHoaDon)
{
    <form method="post">
        <h4>Bạn có muốn xóa hóa đơn có mã @Model.id không? </h4>
        <input type="submit" name="name" value="Xóa" />
    </form>
}
@Model.Chuoi
<br />
<a class="btn btn-info" href="/MH_XuatHang/MH_TimKiem">Quay về tìm kiếm</a>
<a class="btn btn-info" href="/MH_XuatHang/MH_TaoHoaDonXuatHang">Tạo thêm hóa đơn</a>
<br />